name: Linux

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  update:
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            os: ubuntu-26.04
          - arch: arm64
            os: ubuntu-26.04-arm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Read version from version.txt
        shell: bash
        run: echo "NODE_VERSION=$(head -n 1 version.txt | tr -d '\r\n')" >> $GITHUB_ENV

      - name: Setup ccache
        uses: actions/cache@v5
        with:
          path: .ccache
          save-always: true
          key: ${{ github.workflow }}-${{ matrix.arch }}-${{ hashFiles('**/version.txt') }}
          restore-keys: |
            ${{ github.workflow }}-${{ matrix.arch }}-${{ hashFiles('**/version.txt') }}
            ${{ github.workflow }}-${{ matrix.arch }}-

      - name: Install building tools
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y git nodejs python3 python3-pip gcc g++ make nasm ccache

      - name: Run the script
        env:
          ARCH: ${{ matrix.arch }}
          CC: "gcc"
          CXX: "g++"
        run: |
          export CCACHE_COMPRESS="true"
          export CCACHE_BASEDIR="$GITHUB_WORKSPACE"
          export CCACHE_DIR="$CCACHE_BASEDIR/.ccache"
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          mkdir -p "$CCACHE_DIR"

          node index.js

      - name: Create archive
        run: |
          cd node/out/Release
          ln libnode.so.* libnode.so
          ls -lh libnode.* node
          curl -sO https://nodejs.org/dist/${{ env.NODE_VERSION }}/node-${{ env.NODE_VERSION }}-headers.tar.gz
          tar -xzf node-${{ env.NODE_VERSION }}-headers.tar.gz
          mv node-${{ env.NODE_VERSION }}/include ./include
          tar -cJf "libnode-${{ matrix.arch }}-linux.tar.xz" libnode.* node include

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          tag: ${{ env.NODE_VERSION }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: node/out/Release/libnode-${{ matrix.arch }}-linux.tar.xz
