name: Linux

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            os: ubuntu-26.04
          - arch: arm64
            os: ubuntu-26.04-arm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node Version
        uses: ./.github/actions/setup-version

      - name: Restore ccache
        id: ccache
        uses: ./.github/actions/restore-ccache
        with:
          arch: ${{ matrix.arch }}

      - name: Install building tools
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y git python3 python3-pip gcc g++ make nasm ccache

      - name: Build NodeJS
        env:
          ARCH: ${{ matrix.arch }}
        shell: bash
        run: |
          set -o pipefail
          scripts/build.sh 2>&1 | tee build-failure-${{ matrix.arch }}-linux.log

      - name: Create archive
        if: success()
        run: |
          cd node/out/Release
          ln libnode.so.* libnode.so
          ls -lh libnode.* node
          tar -cJf "libnode-${{ matrix.arch }}-linux.tar.xz" libnode.* node

      - name: Handle Release Assets
        if: always()
        uses: ./.github/actions/upload-assets
        with:
          os_name: linux
          arch: ${{ matrix.arch }}
          job_status: ${{ job.status }}
          node_version: ${{ env.NODE_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          archive_path: node/out/Release/libnode-${{ matrix.arch }}-linux.tar.xz

      - name: Save ccache
        if: always()
        uses: ./.github/actions/save-ccache
        with:
          cache-hit: ${{ steps.ccache.outputs.cache-hit }}
          primary-key: ${{ steps.ccache.outputs.cache-primary-key }}