name: Windows

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  update:
    name: Windows
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            os: windows-2025-vs2026
          - arch: arm64
            os: windows-11-vs2026-arm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Read version from version.txt
        shell: bash
        run: echo "NODE_VERSION=$(head -n 1 version.txt | tr -d '\r\n')" >> $GITHUB_ENV

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Setup Ninja
        run: choco install -y python nasm ninja

      - name: Run the script
        env:
          ARCH: ${{ matrix.arch }}
        run: scripts\build.bat

      - name: Create archive
        run: |
          cd node\out\Release
          dir libnode.*, node.*
          7z a -mx9 "libnode-${{ matrix.arch }}-windows.zip" libnode.* node.*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          tag: ${{ env.NODE_VERSION }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: node\out\Release\libnode-${{ matrix.arch }}-windows.zip
          body: |
            Changelog: https://github.com/nodejs/node/releases/tag/${{ env.NODE_VERSION }}
