name: Windows

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  update:
    name: Windows
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            os: windows-2025-vs2026
          - arch: arm64
            os: windows-11-vs2026-arm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node Version
        uses: ./.github/actions/setup-version

      - name: Restore ccache
        id: ccache
        uses: ./.github/actions/restore-ccache
        with:
          arch: ${{ matrix.arch }}

      - name: Setup Scoop
        shell: pwsh
        run: |
          choco install -y 7zip
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          irm get.scoop.sh | iex
          echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          scoop config use_external_7zip true

      - name: Install building tools
        shell: pwsh
        run: |
          scoop install sccache
          choco install -y python nasm ninja

      - name: Build NodeJS
        env:
          ARCH: ${{ matrix.arch }}
        shell: pwsh
        run: |
          cmd.exe /c "scripts\build.bat 2>&1" | Tee-Object -FilePath "build-failure-${{ matrix.arch }}-windows.log"
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

      - name: Create archive
        if: success()
        run: |
          cd node\out\Release
          dir libnode.*, node.*
          7z a -mx9 "libnode-${{ matrix.arch }}-windows.zip" libnode.* node.*

      - name: Handle Release Assets
        if: always()
        uses: ./.github/actions/upload-assets
        with:
          os_name: windows
          arch: ${{ matrix.arch }}
          job_status: ${{ job.status }}
          node_version: ${{ env.NODE_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          archive_path: node\out\Release\libnode-${{ matrix.arch }}-windows.zip

      - name: Save ccache
        if: always()
        uses: ./.github/actions/save-ccache
        with:
          cache-hit: ${{ steps.ccache.outputs.cache-hit }}
          primary-key: ${{ steps.ccache.outputs.cache-primary-key }}